#!/usr/bin/env bash

nextflow run main.nf \
    -profile test \
    --library test_data/library.txt \
    --barcodes test_data/barcodes.txt \
    --inputDir test_data/01_raw \
    --outputDir test_output \
    -resume

OBSERVED='test_output/counts/library/counts_mageck.txt'
EXPECTED='test_data/expected_output.txt'
cmp --silent ${EXPECTED} ${OBSERVED} && \
    echo '--> SUCCESS: Expected Results!' || echo '--> FAILED: Inconsistent Results!'
